"""Subtitle Translator v4 — NLLB-600M GPU batch translator with quality pipeline."""

from translator.engine import (
    __version__,
    _auto_device, safe_open_srt, atomic_save,
    Config,
    find_srt_files, output_path_for, load_json,
    build_xml, parse_xml,
    protect_sfx, restore_sfx,
    protect_short_exclamations, apply_short_exclamation_overrides, _short_excl_replacement,
    protect_song_markers, restore_song_markers, apply_song_markers,
    protect_episode_markers, restore_episode_markers,
    protect_names, restore_names,
    protect_numbers, restore_numbers,
    _segment_line, _reconstruct_line, _segment_texts, _SEGMENT_RE,
    load_glossary, _resolve_glossary_entry, apply_glossary,
    load_names, preserve_names,
    load_german_fixes, apply_german_fixes,
    cleanup_subtitles,
    load_titles, preserve_titles,
    validate, _normalize_line, _rejects_content_addition,
    validate_no_placeholders, _PLACEHOLDER_RE,
    _canonical_restore, _CANONICAL_ZZZ_RE,
    score_line, generate_qa_report,
    load_nllb,
    translate_fast, translate_llm,
    translate_polish, load_polisher, find_suspicious_lines, SUSPICIOUS_THRESHOLD,
    run_test, run_benchmark, run_regression,
    translate_fast_to_texts,
    _checkpoint_path, _save_checkpoint, _load_checkpoint, _remove_checkpoint,
    CONFIG_DIR,
    _CONFIG_CACHE,
    TEST_LINES, EXPECTED,
)

__all__ = [
    "__version__",
    "_auto_device", "safe_open_srt", "atomic_save",
    "Config",
    "find_srt_files", "output_path_for", "load_json",
    "build_xml", "parse_xml",
    "protect_sfx", "restore_sfx",
    "protect_short_exclamations", "apply_short_exclamation_overrides",
    "protect_song_markers", "restore_song_markers", "apply_song_markers",
    "protect_episode_markers", "restore_episode_markers",
    "protect_names", "restore_names",
    "protect_numbers", "restore_numbers",
    "_segment_line", "_reconstruct_line", "_segment_texts", "_SEGMENT_RE",
    "load_glossary", "_resolve_glossary_entry", "apply_glossary",
    "load_names", "preserve_names",
    "load_german_fixes", "apply_german_fixes",
    "cleanup_subtitles",
    "load_titles", "preserve_titles",
    "validate", "_normalize_line", "_rejects_content_addition",
    "validate_no_placeholders", "_PLACEHOLDER_RE",
    "_canonical_restore", "_CANONICAL_ZZZ_RE",
    "score_line", "generate_qa_report",
    "load_nllb",
    "translate_fast", "translate_llm",
    "translate_polish", "load_polisher", "find_suspicious_lines", "SUSPICIOUS_THRESHOLD",
    "run_test", "run_benchmark", "run_regression",
    "translate_fast_to_texts",
    "_checkpoint_path", "_save_checkpoint", "_load_checkpoint", "_remove_checkpoint",
    "CONFIG_DIR",
    "_CONFIG_CACHE",
    "TEST_LINES", "EXPECTED",
]
